name: check_bindata

on: [push, pull_request]

jobs:
  check_bindata:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.2
    
    - name: Install go-bindata
      run: go get github.com/kevinburke/go-bindata/go-bindata@v3.22.0

    - name: check go-bindata
      run: which go-bindata && go-bindata -v
    
    - name: run validation script
      run: ./hack/validate-bindata.sh